#! /bin/bash

NAME=intentgen-fastapi
DIR=/home/ubuntu/intent_generation
USER=ubuntu
GROUP=ubuntu
WORKERS=2
WORKER_CLASS=uvicorn.workers.UvicornWorker
VENV=$DIR/venv/bin/activate
BIND=0.0.0.0:9000
LOG_LEVEL=info

cd $DIR
source $VENV

exec gunicorn app:app \
        --name $NAME \
        --workers $WORKERS \
        --worker-class $WORKER_CLASS \
        --user=$USER \
        --group=$GROUP \
        --bind=$BIND \
        --log-file=-